from pydantic import BaseModel
from typing import List

class Artifact(BaseModel):
    """
    A base class for artifacts generated by the MAS.
    """
    type: str

class DiscoveryBrief(Artifact):
    """
    Represents the structured content of a "Discovery Brief" artifact.
    """
    type: str = "discovery_brief"
    topic: str
    literature_review: str
    # In the future, this could include structured lists of models, datasets, etc.

class AdaptiveTask(BaseModel):
    """
    Represents a single task in an adaptive plan.
    """
    id: str
    type: str
    title: str
    description: str
    estimate: str
    priority: str
    risk: str

class AdaptiveFeature(BaseModel):
    """
    Represents a feature, which is a collection of tasks.
    """
    title: str
    tasks: List[AdaptiveTask]

class AdaptivePlan(Artifact):
    """
    Represents a structured "Adaptive Task Plan" artifact.
    """
    type: str = "adaptive_plan"
    epic_title: str
    features: List[AdaptiveFeature]
